name: Prueba Devops

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        
      - name: Instalacion de Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.10.6
      
      - name: Instalar pytest
        run: pip install pytest
        
      - name: Ejecucion de pytest en un archivo
        run: pytest .github/workflows/test_codigo.py
  
  entrega:
    runs-on: ubuntu-latest
    needs: tests

    steps:

      - name: Comprimir archivos .py
        run: zip entrega.zip *.py  # Crea el archivo zip con todos los scripts Python

      - name: Ver contenido del .zip
        run: unzip -l entrega.zip  # Lista el contenido del archivo zip en la consola

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: entrega-final
          path: entrega.zip

      - name: Mensaje success
        if: success()
        run: echo "Está hecho"
